apiVersion: v1
kind: Service
metadata:
  labels:
    app: 123-test-k8
  name: 123-test-k8
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: 123-test-k8
  type: NodePort