apiVersion: v1
kind: Service
metadata:
  labels:
    app: demok8apioffline
  name: demok8apioffline
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: demok8apioffline
  type: NodePort
