apiVersion: v1
kind: Service
metadata:
  labels:
    app: 123-useragentoffline-testing-ppt-automation
  name: 123-useragentoffline-testing-ppt-automation
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: 123-useragentoffline-testing-ppt-automation
  type: NodePort
