apiVersion: v1
kind: Pod
metadata:
  name: 123-useragentoffline-testing-ppt-automation
  labels:
    app: 123-useragentoffline-testing-ppt-automation
spec:
  containers:
  - name: 123-useragentoffline-testing-ppt-automation
    image: 123-useragentoffline-testing-ppt-automation
    ports:
    - containerPort: 80
    command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
  nodeSelector:
    beta.kubernetes.io/os: linux
