apiVersion: v1
kind: Pod
metadata:
  name: 123-test-k8
  labels:
    app: 123-test-k8
spec:
  containers:
  - name: 123-test-k8
    image: 123-test-k8
    ports:
    - containerPort: 80
    command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
  nodeSelector:
    beta.kubernetes.io/os: linux
