apiVersion: v1
kind: Pod
metadata:
  name: demok8apioffline
  labels:
    app: demok8apioffline
spec:
  containers:
  - name: demok8apioffline
    image: demok8apioffline
    ports:
    - containerPort: 80
    command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
  nodeSelector:
    beta.kubernetes.io/os: linux
